---
title: "Figure4_LOF"
output: html_document
date: "2024-05-03"
---

```{r}
library(data.table)
library(tidyverse)
library(knitr)

source("~/Desktop/Scripts/GeneList_VariantAnnotations.R")

# Set working directory
knitr::opts_knit$set(root.dir = "~/Library/CloudStorage/Box-Box/RVIS/")
setwd("~/Library/CloudStorage/Box-Box/RVIS/")
```

```{r}
source("~/Desktop/Scripts/Compiling_UKB_Data.R")
```

```{r, echo = FALSE}
data.filtered <- data |>
  filter(Function %in% c(SYN, MISSENSE, LOF)) %>% 
  mutate(Maximally_Diverse = ifelse(is.na(diverse_maf), 0, 1)) %>% 
  mutate(nfe_43k = ifelse(is.na(nfe_only_43k_maf), 0, 1)) %>% 
  mutate(nfe_440k = ifelse(is.na(nfe_only_440k_maf), 0, 1)) %>% 
  mutate(all = ifelse(Maximally_Diverse == 1 | nfe_440k == 1, 1, 0)) %>% 
  mutate(afr_MAF = ifelse(is.na(`afr MAF`), 0, 1)) %>% 
  mutate(asj_MAF = ifelse(is.na(`asj MAF`), 0, 1)) %>% 
  mutate(eas_MAF = ifelse(is.na(`eas MAF`), 0, 1)) %>% 
  mutate(sas_MAF = ifelse(is.na(`sas MAF`), 0, 1)) %>% 
  mutate(nfe_20k_MAF = ifelse(is.na(`nfe_20k MAF`), 0, 1))
```

```{r}
ptv <- data.filtered %>% 
  group_by(Gene) %>% 
  filter(Function %in% LOF) %>%
  summarize(Diverse_LOF = sum(Maximally_Diverse, na.rm = T), 
            Nfe_43k_LOF = sum(nfe_43k, na.rm = T),
            Nfe_440k_LOF = sum(nfe_440k, na.rm = T),
            All_LOF = sum(all, na.rm = T),
            afr_LOF = sum(afr_MAF, na.rm = T), 
            asj_LOF = sum(asj_MAF, na.rm = T),
            eas_LOF = sum(eas_MAF, na.rm = T),
            sas_LOF = sum(sas_MAF, na.rm = T),
            nfe_20k_LOF = sum(nfe_20k_MAF, na.rm = T)
            ) %>% 
  arrange(Gene)
```

```{r}
pos <- gnomad.metrics %>% 
  select(gene, possible_lof, mu_mis, mu_syn, mu_lof) %>% 
  rename("Gene" = gene)

df <- ptv %>% 
  left_join(pos, by = "Gene")
```

```{r}
LOF_OE <- df %>%
  mutate(
    `Maximally Diverse (n=43k)` = Diverse_LOF / (possible_lof + possible_lof*1.25),
    `NFE (n=43k)` = Nfe_43k_LOF / (possible_lof + possible_lof*1.25),
    `NFE (n=440k)` = Nfe_440k_LOF / (possible_lof + possible_lof*1.25),
    `Full Dataset (n=460k)` = All_LOF / (possible_lof + possible_lof*1.25),
    
    AFR = afr_LOF / (possible_lof + possible_lof*1.25),
    ASJ = asj_LOF / (possible_lof + possible_lof*1.25),
    EAS = eas_LOF / (possible_lof + possible_lof*1.25),
    SAS = sas_LOF / (possible_lof + possible_lof*1.25),
    `NFE (n=20k)` = nfe_20k_LOF / (possible_lof + possible_lof*1.25)
  ) %>%
  select(Gene, `Maximally Diverse (n=43k)`, `NFE (n=43k)`, `NFE (n=440k)`, `Full Dataset (n=460k)`, AFR, ASJ, EAS, SAS, `NFE (n=20k)`)
```


```{r}
LOF_OE_combined <- df %>%
  mutate(
    LOF_OE_Diverse43k = Diverse_LOF / (possible_lof + possible_lof*1.25),
    LOF_OE_NFE43k = Nfe_43k_LOF / (possible_lof + possible_lof*1.25),
    LOF_OE_NFE440k = Nfe_440k_LOF / (possible_lof + possible_lof*1.25),
    LOF_OE_FullDataset = All_LOF / (possible_lof + possible_lof*1.25),
    
    LOF_OE_AFR = afr_LOF / (possible_lof + possible_lof*1.25),
    LOF_OE_ASJ = asj_LOF / (possible_lof + possible_lof*1.25),
    LOF_OE_EAS = eas_LOF / (possible_lof + possible_lof*1.25),
    LOF_OE_SAS = sas_LOF / (possible_lof + possible_lof*1.25),
    LOF_OE_NFE20k = nfe_20k_LOF / (possible_lof + possible_lof*1.25)
  )
```

```{r}
write.csv(LOF_OE_combined, "LOF_OE_Score.csv", row.names = FALSE)
```

```{r}
source("~/Desktop/Scripts/UKB_LOF.R")
```

```{r}
dee_results <- PrintAUC(LOF_OE, score_cols, dee_monoallelic)
dee_AUC <- dee_results$auc_df %>% 
  rename(`DEE Monoallelic\n (n=94)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
dee_delong <- dee_results$delong_results %>% 
  mutate(Gene_List = "DEE Monoallelic") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)


dd_results <- PrintAUC(LOF_OE, score_cols, dd_monoallelic)
dd_AUC <- dd_results$auc_df %>% 
  rename(`DD Monoallelic\n (n=435)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
dd_delong <- dd_results$delong_results %>% 
  mutate(Gene_List = "DD Monoallelic") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)


asd_results <- PrintAUC(LOF_OE, score_cols, asd_monoallelic)
asd_AUC <- asd_results$auc_df %>% 
  rename(`ASD Monoallelic\n (n=190)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
asd_delong <- asd_results$delong_results %>% 
  mutate(Gene_List = "ASD Monoallelic") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)


mgi_results <- PrintAUC(LOF_OE, score_cols, mgi_essential)
mgi_AUC <- mgi_results$auc_df %>% 
  rename(`Mouse Essential\n (n=2454)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
mgi_delong <- mgi_results$delong_results %>% 
  mutate(Gene_List = "Mouse Essential") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)


HI_results <- PrintAUC(LOF_OE, score_cols, clingen_HI)
HI_AUC <- HI_results$auc_df %>% 
  rename(`Haploinsufficient\n (n=360)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
HI_delong <- HI_results$delong_results %>% 
  mutate(Gene_List = "Haploinsufficient") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)
```

```{r}
LOF_OE_AUC <- rbind(dee_AUC, dd_AUC, asd_AUC, mgi_AUC, HI_AUC)
LOF_OE_AUC <- LOF_OE_AUC %>% 
  rename("Ancestry" = score)
```

```{r}
delongtest <- rbind(dee_delong, dd_delong, asd_delong, mgi_delong, HI_delong)
delongtest

write.csv(delongtest, "LOF_OE_DeLong_test.csv", row.names = FALSE)
```


```{r}
dee_AUC <- PrintLogRegResults(LOF_OE, score_cols, dee_monoallelic) %>% 
  mutate(`Gene List` = "DEE Monoallelic") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)

dd_AUC <- PrintLogRegResults(LOF_OE, score_cols, dd_monoallelic) %>% 
  mutate(`Gene List` = "DD Monoallelic") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)

asd_AUC <- PrintLogRegResults(LOF_OE, score_cols, asd_monoallelic) %>% 
  mutate(`Gene List` = "ASD Monoallelic") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)

mgi_AUC <- PrintLogRegResults(LOF_OE, score_cols, mgi_essential) %>% 
  mutate(`Gene List` = "Mouse Essential") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)

HI_AUC <- PrintLogRegResults(LOF_OE, score_cols, clingen_HI) %>% 
  mutate(`Gene List` = "Haploinsufficient") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)
```

```{r}
UKB_LOF_OE_log <- rbind(dee_AUC, dd_AUC, asd_AUC, mgi_AUC, HI_AUC)
UKB_LOF_OE_log <- UKB_LOF_OE_log %>% 
  rename("Ancestry" = score)
```

```{r}
write.csv(UKB_LOF_OE_log, file = "~/Library/CloudStorage/Box-Box/Dhindsa Lab/RVIS/UKB_LOF_OE_log_regression.csv")
```


# Figure 4a: UKBiobank RVIS Performances by Ancestry
```{r}
a <- PrintGraph(LOF_OE_AUC, "DEE Monoallelic\n (n=94)") + theme(legend.position = "none") 
b <- PrintGraph(LOF_OE_AUC, "DD Monoallelic\n (n=435)") + theme(legend.position = "none") + labs(y = "")
c <- PrintGraph(LOF_OE_AUC, "ASD Monoallelic\n (n=190)") + theme(legend.position = "none") + labs(y = "")
d <- PrintGraph(LOF_OE_AUC, "Haploinsufficient\n (n=360)") + theme(legend.position = "none") + labs(y = "")
e <- PrintGraph(LOF_OE_AUC, "Mouse Essential\n (n=2454)") + theme(legend.position = "none") + labs(y = "")

library(patchwork)

patch1 <- (a|b|c|d|e)
  
patch1
```

```{r}
total_var <- data.filtered %>% 
  group_by(Gene) %>% 
  summarize(total_var = n())

df <- df %>% 
  left_join(total_var, by = "Gene")
```

```{r}
LOF_FDR <- df %>%
  mutate(
    `Maximally Diverse (n=43k)` = (Diverse_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)) ,
    `NFE (n=43k)` = (Nfe_43k_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    `NFE (n=440k)` = (Nfe_440k_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    `Full Dataset (n=460k)` = (All_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    
    AFR = (afr_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)) ,
    ASJ = (asj_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    EAS = (eas_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    SAS = (sas_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    `NFE (n=20k)` = (nfe_20k_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis))
  ) %>%
  select(Gene, `Maximally Diverse (n=43k)`, `NFE (n=43k)`, `NFE (n=440k)`, `Full Dataset (n=460k)`, AFR, ASJ, EAS, SAS, `NFE (n=20k)`)
```


```{r}
LOF_FDR_combined <- df %>%
  mutate(
    LOF_FDR_Diverse43k = (Diverse_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)) ,
    LOF_FDR_NFE43k = (Nfe_43k_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    LOF_FDR_NFE440k = (Nfe_440k_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    LOF_FDR_FullDataset = (All_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    
    LOF_FDR_AFR = (afr_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)) ,
    LOF_FDR_ASJ = (asj_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    LOF_FDR_EAS = (eas_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    LOF_FDR_SAS = (sas_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis)),
    LOF_FDR_NFE20k = (nfe_20k_LOF/total_var)/((mu_lof+mu_lof*1.25)/((mu_lof+mu_lof*1.25)+mu_syn+mu_mis))
  )
```

```{r}
write.csv(LOF_FDR_combined, "LOF_FDR_Score.csv", row.names = FALSE)
```


```{r}
dee_results <- PrintAUC(LOF_FDR, score_cols, dee_monoallelic)
dee_AUC <- dee_results$auc_df %>% 
  rename(`DEE Monoallelic\n (n=94)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
dee_delong <- dee_results$delong_results %>% 
  mutate(Gene_List = "DEE Monoallelic") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)


dd_results <- PrintAUC(LOF_FDR, score_cols, dd_monoallelic)
dd_AUC <- dd_results$auc_df %>% 
  rename(`DD Monoallelic\n (n=435)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
dd_delong <- dd_results$delong_results %>% 
  mutate(Gene_List = "DD Monoallelic") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)


asd_results <- PrintAUC(LOF_FDR, score_cols, asd_monoallelic)
asd_AUC <- asd_results$auc_df %>% 
  rename(`ASD Monoallelic\n (n=190)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
asd_delong <- asd_results$delong_results %>% 
  mutate(Gene_List = "ASD Monoallelic") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)


mgi_results <- PrintAUC(LOF_FDR, score_cols, mgi_essential)
mgi_AUC <- mgi_results$auc_df %>% 
  rename(`Mouse Essential\n (n=2454)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
mgi_delong <- mgi_results$delong_results %>% 
  mutate(Gene_List = "Mouse Essential") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)


HI_results <- PrintAUC(LOF_FDR, score_cols, clingen_HI)
HI_AUC <- HI_results$auc_df %>% 
  rename(`Haploinsufficient\n (n=360)` = AUC) %>% 
  pivot_longer(cols = -1, names_to = "Gene List", values_to = "AUC")
HI_delong <- HI_results$delong_results %>% 
  mutate(Gene_List = "Haploinsufficient") %>% 
  select(Gene_List, Score1, Score2, De.Long.P.val)
```

```{r}
LOF_FDR_AUC <- rbind(dee_AUC, dd_AUC, asd_AUC, mgi_AUC, HI_AUC)
LOF_FDR_AUC <- LOF_FDR_AUC %>% 
  rename("Ancestry" = score)
```

```{r}
delongtest <- rbind(dee_delong, dd_delong, asd_delong, mgi_delong, HI_delong)
delongtest

write.csv(delongtest, "LOF_FDR_DeLong_test.csv", row.names = FALSE)
```


```{r}
dee_AUC <- PrintLogRegResults(LOF_FDR, score_cols, dee_monoallelic) %>% 
  mutate(`Gene List` = "DEE Monoallelic") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)

dd_AUC <- PrintLogRegResults(LOF_FDR, score_cols, dd_monoallelic) %>% 
  mutate(`Gene List` = "DD Monoallelic") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)

asd_AUC <- PrintLogRegResults(LOF_FDR, score_cols, asd_monoallelic) %>% 
  mutate(`Gene List` = "ASD Monoallelic") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)

mgi_AUC <- PrintLogRegResults(LOF_FDR, score_cols, mgi_essential) %>% 
  mutate(`Gene List` = "Mouse Essential") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)

HI_AUC <- PrintLogRegResults(LOF_FDR, score_cols, clingen_HI) %>% 
  mutate(`Gene List` = "Haploinsufficient") %>% 
  select(score, `Gene List`, Log.Reg.P.val, AUC)
```

```{r}
UKB_LOF_FDR_log <- rbind(dee_AUC, dd_AUC, asd_AUC, mgi_AUC, HI_AUC)
UKB_LOF_FDR_log <- UKB_LOF_FDR_log %>% 
  rename("Ancestry" = score)
```

```{r}
write.csv(UKB_LOF_FDR_log, file = "~/Library/CloudStorage/Box-Box/Dhindsa Lab/RVIS/UKB_LOF_FDR_log_regression.csv")
```



# Figure 4: UKBiobank RVIS Performances by Ancestry
```{r}
a <- PrintGraph(LOF_FDR_AUC, "DEE Monoallelic\n (n=94)") + theme(legend.position = "none") 
b <- PrintGraph(LOF_FDR_AUC, "DD Monoallelic\n (n=435)") + theme(legend.position = "none") + labs(y = "")
c <- PrintGraph(LOF_FDR_AUC, "ASD Monoallelic\n (n=190)") + theme(legend.position = "none") + labs(y = "")
d <- PrintGraph(LOF_FDR_AUC, "Haploinsufficient\n (n=360)") + theme(legend.position = "none") + labs(y = "")
e <- PrintGraph(LOF_FDR_AUC, "Mouse Essential\n (n=2454)") + theme(legend.position = "none") + labs(y = "")

patch2 <- (a|b|c|d|e)

patch2
```

```{r}
figure4a <- patch1 + plot_annotation('A')
figure4b <- patch2 + plot_annotation('B')
```

```{r}
ggsave("Figure4a.pdf", plot = figure4a, width = 174, height = 87, units = "mm")
ggsave("Figure4b.pdf", plot = figure4b, width = 174, height = 87, units = "mm")
```